import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join, relative } from "node:path";
import { ACTION_HARDENING_SPEC } from "./action-hardening-spec";
import { discoverActionRegistry, generatedReleaseDirectory, repositoryRoot, writeDiscoveredActionManifest } from "./discover-action-registry";

function markdownTable(rows: Array<Record<string, string | number | boolean | null>>): string {
  const headers = ["#", "Plugin", "Action type", "Profile", "Approval floor", "Capability family", "External", "Receipt", "Registry source", "Schema source"];
  const rendered = rows.map((row) => [
    row.number,
    `\`${row.plugin}\``,
    `\`${row.actionType}\``,
    `\`${row.profile}\``,
    `\`${row.approvalFloor}\``,
    `\`${row.capabilityFamily}\``,
    row.external ? "yes" : "no",
    row.receipt ? "yes" : "no",
    `${row.sourcePath}:${row.sourceLine}`,
    row.schemaSourcePath ? `${row.schemaSourcePath}:${row.schemaSourceLine}` : "not declared",
  ]);
  return [
    `| ${headers.join(" | ")} |`,
    `| ${headers.map(() => "---").join(" | ")} |`,
    ...rendered.map((row) => `| ${row.join(" | ")} |`),
  ].join("\n");
}

export async function verifyActionManifest(): Promise<void> {
  const discovered = await discoverActionRegistry();
  await writeDiscoveredActionManifest(discovered);
  const expectedByAction = new Map(ACTION_HARDENING_SPEC.map((row) => [row.actionType, row]));
  const discoveredByAction = new Map(discovered.map((row) => [row.actionType, row]));
  const missing = ACTION_HARDENING_SPEC.filter((row) => !discoveredByAction.has(row.actionType));
  const unexpected = discovered.filter((row) => !expectedByAction.has(row.actionType));
  const ownershipMismatch = ACTION_HARDENING_SPEC.filter((row) => discoveredByAction.get(row.actionType)?.plugin !== row.plugin);
  if (ACTION_HARDENING_SPEC.length !== 44) throw new Error(`Fixed spec has ${ACTION_HARDENING_SPEC.length} rows; expected 44.`);
  if (discovered.length !== 44 || missing.length || unexpected.length || ownershipMismatch.length) {
    const details = [
      `discovered=${discovered.length}`,
      `missing=${missing.map((row) => row.actionType).join(",") || "none"}`,
      `unexpected=${unexpected.map((row) => row.actionType).join(",") || "none"}`,
      `ownershipMismatch=${ownershipMismatch.map((row) => `${row.actionType}:${discoveredByAction.get(row.actionType)?.plugin ?? "missing"}->${row.plugin}`).join(",") || "none"}`,
    ];
    throw new Error(`Action manifest mismatch: ${details.join("; ")}`);
  }

  await mkdir(generatedReleaseDirectory, { recursive: true });
  const rows = ACTION_HARDENING_SPEC.map((spec, index) => ({ number: index + 1, ...spec, ...discoveredByAction.get(spec.actionType)! }));
  const document = [
    "# JARVIS Action Manifest",
    "",
    "Generated by `npm run release:manifest`. It compares the static domain-plugin registry discovery to the fixed 44-row P0 release specification.",
    "",
    `Result: **PASS** — ${rows.length}/44 action types match name and plugin ownership.`,
    "",
    markdownTable(rows),
    "",
  ].join("\n");
  const markdownPath = join(generatedReleaseDirectory, "action-manifest.md");
  await writeFile(markdownPath, document);
  const json = JSON.parse(await readFile(join(generatedReleaseDirectory, "action-manifest.json"), "utf8")) as { actionCount: number };
  if (json.actionCount !== 44) throw new Error(`Written JSON manifest count is ${json.actionCount}; expected 44.`);
  console.log(`PASS: fixed spec and discovered registry match 44/44 (${relative(repositoryRoot, markdownPath)})`);
}

void verifyActionManifest().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
