// Phase 4 (§4.2): real PDF rendering via pdf-lib — replaces the honestly-labeled
// hand-built placeholder (packages/tools/src/docusign.ts's buildPlaceholderPdf, a
// title string with no real content). This is the "internal real implementation"
// the pack calls for: Postgres-backed (packages/db/schema.ts's document_contents,
// migration 0025), no external storage or rendering provider needed or in scope.

import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

export interface PdfLineItem {
  label: string;
  quantity: number;
  unitPriceUsd: number;
}

export interface GenericDocumentContent {
  kind: "generic";
  title: string;
}

export interface ProposalDocumentContent {
  kind: "proposal";
  title: string;
  householdAddress: string;
  lineItems: PdfLineItem[];
  totalUsd: number;
  validUntil: string | null;
}

export type DocumentContent = GenericDocumentContent | ProposalDocumentContent;

const MARGIN = 50;
const PAGE_WIDTH = 612; // US Letter
const PAGE_HEIGHT = 792;

async function baseDoc() {
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  const page = doc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  return { doc, font, bold, page };
}

/** Renders a real, parseable PDF (magic header, real content stream — not a
 *  placeholder string) for any document kind. Proposal content gets real line-item
 *  rendering; anything else gets a real, honestly-generic single-page document. */
export async function renderDocumentPdf(content: DocumentContent): Promise<Buffer> {
  const { doc, font, bold, page } = await baseDoc();
  let y = PAGE_HEIGHT - MARGIN;

  page.drawText("FINNOR WATER CO.", { x: MARGIN, y, size: 10, font: bold, color: rgb(0.2, 0.4, 0.5) });
  y -= 30;
  page.drawText(content.title, { x: MARGIN, y, size: 18, font: bold });
  y -= 30;

  if (content.kind === "generic") {
    page.drawText("This document was generated by Finnor JARVIS.", { x: MARGIN, y, size: 11, font });
    const bytes = await doc.save();
    return Buffer.from(bytes);
  }

  page.drawText(`Prepared for: ${content.householdAddress}`, { x: MARGIN, y, size: 11, font });
  y -= 18;
  if (content.validUntil) {
    page.drawText(`Valid until: ${new Date(content.validUntil).toLocaleDateString("en-US")}`, { x: MARGIN, y, size: 11, font });
    y -= 18;
  }
  y -= 12;

  page.drawLine({ start: { x: MARGIN, y }, end: { x: PAGE_WIDTH - MARGIN, y }, thickness: 1, color: rgb(0.7, 0.7, 0.7) });
  y -= 20;
  page.drawText("Item", { x: MARGIN, y, size: 10, font: bold });
  page.drawText("Qty", { x: 350, y, size: 10, font: bold });
  page.drawText("Unit Price", { x: 410, y, size: 10, font: bold });
  page.drawText("Amount", { x: 500, y, size: 10, font: bold });
  y -= 16;

  for (const item of content.lineItems) {
    if (y < MARGIN + 60) break; // real overflow guard — a genuinely long quote truncates rather than drawing off-page
    const amount = item.quantity * item.unitPriceUsd;
    page.drawText(item.label.slice(0, 45), { x: MARGIN, y, size: 10, font });
    page.drawText(String(item.quantity), { x: 350, y, size: 10, font });
    page.drawText(`$${item.unitPriceUsd.toFixed(2)}`, { x: 410, y, size: 10, font });
    page.drawText(`$${amount.toFixed(2)}`, { x: 500, y, size: 10, font });
    y -= 16;
  }

  y -= 10;
  page.drawLine({ start: { x: MARGIN, y }, end: { x: PAGE_WIDTH - MARGIN, y }, thickness: 1, color: rgb(0.7, 0.7, 0.7) });
  y -= 20;
  page.drawText("Total", { x: 410, y, size: 12, font: bold });
  page.drawText(`$${content.totalUsd.toFixed(2)}`, { x: 500, y, size: 12, font: bold });

  const bytes = await doc.save();
  return Buffer.from(bytes);
}
