// GET /api/documents/:id — real document bytes, tenant-scoped (Phase 4 §4.2). Proves
// "artifacts retrievable" isn't just a claim: this serves the actual PDF bytes
// generated by the native documents binding (packages/tools/src/capabilities/
// documents.ts), not a stub.

import { withTenant, documents } from "@finnor/db";
import { getDocumentContent } from "@finnor/data-platform";
import { and, eq } from "drizzle-orm";
import { requireContext, errorResponse } from "../../../../lib/auth";

export async function GET(req: Request, { params }: { params: { id: string } }): Promise<Response> {
  try {
    const ctx = await requireContext(req);
    const result = await withTenant(ctx.tenantId, async (db) => {
      const [doc] = await db
        .select()
        .from(documents)
        .where(and(eq(documents.id, params.id), eq(documents.tenantId, ctx.tenantId)));
      if (!doc) return null;
      const content = await getDocumentContent(db, params.id);
      return { doc, content };
    });
    if (!result || !result.content) return Response.json({ error: "Document not found or has no content yet" }, { status: 404 });
    return new Response(new Uint8Array(result.content.bytes), {
      status: 200,
      headers: {
        "content-type": result.content.contentType,
        "content-disposition": `inline; filename="${result.doc.kind}-${params.id}.pdf"`,
        "cache-control": "private, max-age=3600",
      },
    });
  } catch (err) {
    return errorResponse(err);
  }
}
