import { expect, test } from "@playwright/test"

test.describe("Tenant Experience Manifest V2 reference compositions", () => {
  test.beforeEach(async ({ page }, testInfo) => {
    test.skip(testInfo.project.name !== "desktop-chromium", "one deterministic reference composition pass")
    await page.addInitScript(() => window.localStorage.setItem("jarvis_admin_key", "reference-fixture-key"))
    await page.route("**/api/jarvis/**", async (route) => {
      const path = new URL(route.request().url()).pathname
      if (path.endsWith("/read-models/work-cases")) return route.fulfill({ json: { data: [] } })
      if (path.endsWith("/actions/pending")) return route.fulfill({ json: { actions: [] } })
      if (path.endsWith("/workflows/runs")) return route.fulfill({ json: { runs: [] } })
      if (path.endsWith("/stats")) return route.fulfill({ json: { pending: 0, blocked: 0, recentActions: [] } })
      if (path.includes("/read-models/")) return route.fulfill({ status: 401, json: { error: "fixture has no private session" } })
      return route.continue()
    })
  })

  test("Northstar and Summit produce materially different Ready experiences from one registry", async ({ page }) => {
    const governedInstructions: unknown[] = []
    await page.route("**/api/jarvis/actions", async (route) => {
      if (route.request().method() !== "POST") return route.continue()
      governedInstructions.push(await route.request().postDataJSON())
      return route.fulfill({ json: { planned: [], workId: "fixture-work", instructionId: "fixture-instruction" } })
    })
    await page.route("**/api/jarvis/instructions/*/events**", (route) => route.fulfill({ json: { events: [] } }))
    await page.goto("/jarvis/fixtures/tenant-experience/northstar", { waitUntil: "domcontentloaded" })
    const northstar = page.locator("[data-tenant-experience-fixture='northstar']")
    await expect(northstar.locator("[data-ready-focus='service']")).toBeVisible()
    await expect(northstar.locator("[data-client-overlay='northstar-service-priority']").first()).toContainText("Service response priorities")
    await expect(northstar.getByRole("link", { name: "Households" })).toBeVisible()
    await expect(northstar.locator("[data-metric-key='overdue_invoice_value']")).toBeVisible()
    await expect(northstar).toHaveAttribute("data-jarvis-experience-density", "compact")
    await expect(northstar.locator("img[src*='reference-northstar.svg']")).toBeVisible()
    await northstar.getByRole("button", { name: "Review service calls" }).click()
    await expect.poll(() => governedInstructions.length).toBe(1)
    expect(governedInstructions[0]).toMatchObject({ instruction: "Show today’s schedule", channel: "text" })
    await northstar.getByLabel("Continuity probe").fill("active-workspace-state")
    await northstar.getByRole("button", { name: "Show dispatcher" }).click()
    await expect(northstar.locator("[data-ready-focus='dispatch']")).toBeVisible()
    await expect(northstar.getByRole("link", { name: "Cash" })).toHaveCount(0)
    await northstar.getByRole("button", { name: "Show technician" }).click()
    await expect(northstar.locator("[data-ready-focus='assigned_work']")).toBeVisible()
    await expect(northstar.locator("[data-metric-key='assigned_work_today']")).toBeVisible()
    await northstar.getByRole("button", { name: "Show owner" }).click()
    await northstar.getByRole("button", { name: "Apply Summit config" }).click()
    const summit = page.locator("[data-tenant-experience-fixture='summit']")
    await expect(summit.locator("[data-ready-focus='inventory']")).toBeVisible()
    await expect(summit.locator("[data-client-overlay='summit-installation-readiness']").first()).toContainText("Materials lens")
    await expect(summit.getByRole("link", { name: "Accounts" })).toBeVisible()
    await expect(summit.locator("[data-metric-key='stock_risk_items']")).toBeVisible()
    await expect(summit).toHaveAttribute("data-jarvis-experience-density", "spacious")
    await expect(summit.locator("img[src*='reference-summit.svg']")).toBeVisible()
    await expect(summit.getByText("no reference business results are supplied", { exact: false })).toBeVisible()
    await expect(summit.getByLabel("Continuity probe")).toHaveValue("active-workspace-state")
  })
})
