// Regenerates packages/db/migrations-bundle.ts from the SQL files — run after adding
// a migration. The bundle exists because serverless functions can't read the SQL
// directory from disk; importing the bundle traces it into the deployment.
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const dir = join(root, "packages/db/migrations");
const files = readdirSync(dir).filter((f) => f.endsWith(".sql")).sort();
const entries = files.map((name) => {
  const sql = readFileSync(join(dir, name), "utf8");
  return `  { name: ${JSON.stringify(name)}, sql: ${JSON.stringify(sql)} },`;
});
const out = `// AUTO-GENERATED by scripts/bundle-migrations.ts — do not edit by hand.
import type { MigrationFile } from "./migrate";

export const MIGRATIONS: MigrationFile[] = [
${entries.join("\n")}
];
`;
writeFileSync(join(root, "packages/db/migrations-bundle.ts"), out);
console.log(`bundled ${files.length} migrations`);
